name = "solongandthanksforallthe_fish"
account_id = "28b639294a6959cfb08ba53249e9ae7f"
type = "webpack"
workers_dev = true

[site]
bucket = "./build"
entry-point = "./workers-site"

[env.production]
zone_id = "0a2bb699c0fac65b39b54b81d72189d8"
route = "solongandthanksforallthe.fish/*"

